<script setup>
import Sprite from './Sprite.vue';import {byId,customers,money} from '../../../shared/data.js';defineProps({g:Object});
</script>
<template>
 <section class="workbench"><div class="work-head"><div><span class="eyebrow">GÓC CHẾ BIẾN</span><h2>{{g.dish?.name||'Thau trộn sẵn sàng'}}</h2></div><span class="pill">{{g.dish?{mix:'Trộn',grill:'Nướng',roll:'Cuốn'}[g.dish.method]:'Chờ nhận đơn'}}</span></div>
 <div class="work-content"><div class="station"><div class="station-circle" :class="{ready:g.r.phase==='ready'}"><div class="dish" :class="{cooking:g.r.phase==='cook','grill-dish':g.dish?.method==='grill'}" :style="g.dish?.method==='grill'?{filter:`sepia(${Math.max(...g.r.grill.sides)*.4}) brightness(${1-Math.max(...g.r.grill.sides)*.45})`}:{}"><Sprite :index="g.dish?.sprite||12"/></div><span v-for="(id,i) in g.r.selected" :key="id" class="tiny-topping" :style="{'--i':i}"><Sprite :index="byId(id).sprite"/></span><span class="sparkle">✧</span></div><div class="station-label">{{g.r.phase==='ready'?(g.quality?'Thơm quá! Mang ra thôi ♡':'Món chưa đạt — làm lại nhé'):g.r.phase==='cook'?'Khéo tay cho món thật ngon':g.r.selected.length?`${g.r.selected.length} nguyên liệu trong thau`:'Thêm một chút ngon vào đây'}}</div></div>
 <div class="recipe-work"><template v-if="g.dish"><p class="customer-quote">“{{customers[g.current.customer].line}}”</p><div class="recipe-label"><b>Đơn của {{customers[g.current.customer].name}}</b><span>{{money(g.dish.price)}}</span></div><div class="recipe-chips"><span v-for="id in g.dish.ingredients" :key="id" :class="{checked:g.r.selected.includes(id)}">{{g.r.selected.includes(id)?'✓':'＋'}} {{byId(id).name}}</span></div><div class="steps"><span :class="{now:g.r.phase==='select'}">1. Nguyên liệu</span><span :class="{now:['cut','cook'].includes(g.r.phase)}">2. Chế biến</span><span :class="{now:g.r.phase==='ready'}">3. Phục vụ</span></div>
 <template v-if="g.r.phase==='select'"><p class="hint">Chọn đủ nguyên liệu bên dưới. Chạm lại để bỏ chọn.</p><button class="primary wide" :disabled="!g.r.selected.length" @click="g.prepare">{{g.dish.method==='mix'?'✂ Bắt đầu cắt bánh':g.dish.method==='grill'?'Bắt đầu nướng':'Bắt đầu cuốn'}}</button></template>
 <template v-else-if="g.r.phase==='cut'"><p class="hint">Cắt {{Math.max(0,3-g.s.upgrades.tools-g.r.cut)}} lần nữa. Có thể dùng phím Space.</p><button class="primary wide" @click="g.cut">✂ Cắt bánh</button></template>
 <template v-else-if="g.r.phase==='cook'"><template v-if="g.dish.method==='grill'"><p class="hint">Nướng cả hai mặt. Vùng xanh 62–82% là ngon nhất; 100% sẽ cháy.</p><div class="heat-controls"><span>{{Math.round(g.r.grill.temperature)}}°C</span><button v-for="n in 3" :key="n" :class="{selected:g.r.grill.power===n}" :aria-pressed="g.r.grill.power===n" @click="g.r.grill.power=n">{{['Lửa nhỏ','Vừa','Lớn'][n-1]}}</button></div><div class="grill-meters"><div v-for="(v,i) in g.r.grill.sides" :key="i"><span>Mặt {{i+1}}{{g.r.grill.side===i?' · đang nướng':''}}</span><div class="doneness"><i :style="{width:Math.min(v,1)*100+'%'}"></i><b class="grill-zone"></b></div><small>{{Math.round(v*100)}}%</small></div></div><div class="button-row"><button class="secondary" @click="g.r.grill.side=1-g.r.grill.side;g.play('roll')">↶ Lật bánh</button><button class="primary" @click="g.hit">♨ Nhấc bánh</button></div></template>
 <template v-else><p class="hint">Chạm khi kim ở vùng xanh. {{g.r.hits.length}}/{{Math.max(1,3-g.s.upgrades.tools)}} nhịp.</p><div class="timing"><div class="sweet-zone"></div><b id="needle" :style="{left:g.meter*100+'%'}"></b></div><button class="primary wide" @click="g.hit">{{g.dish.method==='roll'?'↻ Cuốn bánh':'↻ Trộn nào!'}}</button></template></template>
 <template v-else><p class="quality">{{'★'.repeat(g.quality)||'Chưa đạt'}}<span>{{g.quality?'Món ăn đã sẵn sàng':'Bánh sống hoặc cháy không được thanh toán.'}}</span></p><button v-if="g.quality" class="primary wide" @click="g.serve">✓ Phục vụ khách</button><button v-else class="primary wide" @click="g.discard">Làm lại món</button></template>
 <div class="sub-actions"><button class="text-btn" @click="g.r.phase==='select'?g.discard():g.dialog='discard'">Làm lại</button><button class="text-btn" @click="g.dialog='book'">Sổ công thức</button></div></template>
 <div v-else class="empty-station"><span>✦</span><h3>Món ngon bắt đầu từ bạn</h3><p>Nhận đơn của một vị khách phía trên.<br>Công thức sẽ xuất hiện ngay ở đây.</p><button class="secondary" @click="g.s.started?g.dialog='book':g.start()">{{g.s.started?'Mở sổ công thức':'Mở cửa tiệm'}}</button></div></div></div>
 <div class="ingredient-head"><h3>Khay nguyên liệu <small>Chạm để thêm</small></h3><div class="filters"><button v-for="([id,label]) in [['all','Tất cả'],['base','Bánh'],['top','Topping'],['veg','Rau'],['sauce','Sốt']]" :key="id" :class="{selected:g.filter===id}" @click="g.filter=id">{{label}}</button></div></div><div class="ingredients"><button v-for="i in g.ingredientList" :key="i.id" class="ingredient" :class="{chosen:g.r.selected.includes(i.id)}" :disabled="!g.current||g.r.phase!=='select'||g.s.inventory[i.id].reduce((n,b)=>n+b.qty,0)===0" @click="g.ingredient(i.id)"><Sprite :index="i.sprite"/><b>{{i.name}}</b><small>{{g.r.selected.includes(i.id)?'✓ Đã chọn':`Còn ${g.s.inventory[i.id].reduce((n,b)=>n+b.qty,0)}`}}</small></button></div>
 </section>
</template>
