<script setup>
import {reactive,ref,computed,watch,nextTick,onMounted} from 'vue';import {useGame} from './composables/useGame.js';import Sprite from './components/Sprite.vue';import Station from './components/Station.vue';import AccountPanel from './components/AccountPanel.vue';import {items,recipes,recipe,customers,upgrades,money} from '../../shared/data.js';import {count,validateSave} from '../../shared/engine.js';import {stories,storyMilestones} from '../../shared/mechanics.js';import {asset,loadMedia} from './services/media.js';
const g=reactive(useGame()),modal=ref(null),pending=ref(null),dice=ref(null),mobileTab=ref('street');const names=['Gánh nhỏ đầu hẻm','Quán cóc thân quen','Tiệm bánh & trà','Góc phố nổi tiếng'];
const progress=computed(()=>g.shopLevel===4?100:g.shopLevel===1?g.s.served/6*100:g.shopLevel===2?(g.s.served-6)/10*100:(g.s.served-16)/19*100);
const titles={stock:'Ghé chợ đầu hẻm',upgrades:'Chăm chút tiệm nhỏ',book:'Sổ tay vị ngon',stories:'Những người thương tiệm',fun:'Nghỉ tay một chút',settings:'Một góc theo ý bạn',cloud:'Liên kết tài khoản',end:'Dọn tiệm, đón ngày mới',help:'Chủ tiệm ơi, bắt đầu nhé!',level:'Tiệm mình lớn thêm rồi!',discard:'Làm lại món này?',reset:'Bắt đầu một tiệm mới?',import:'Thay thế tiến trình hiện tại?'};
watch(()=>g.dialog,async v=>{await nextTick();if(v&&!modal.value.open)modal.value.showModal();else if(!v&&modal.value.open)modal.value.close()});
watch(()=>g.current,v=>{if(v)mobileTab.value='cook';});
function onSelectCustomer(id){g.selectOrder(id);mobileTab.value='cook';}
async function importFile(e){try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('Tệp quá lớn.');const data=JSON.parse(await file.text());if(!validateSave(data))throw Error('Tệp bản lưu không hợp lệ.');pending.value=data;g.dialog='import'}catch(err){g.notify(err.message)}finally{e.target.value=''}}
function imported(){g.replaceState(pending.value);pending.value=null;g.dialog='';g.notify('Đã nhập bản lưu.');}
function backgroundClose(e){if(e.target===modal.value){const b=modal.value.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)g.dialog='';}}
onMounted(loadMedia);
</script>
<template>
<div class="game-root" :style="{'--atlas-image':`url('${asset('atlas.webp')}'), url('/assets/atlas.webp')`,'--street-image':`url('${asset('street.webp')}'), url('/assets/street.webp')`}" @pointerdown.capture="g.unlock" @keydown.capture="g.unlock">
<header class="topbar"><a class="brand" href="./"><Sprite :index="12" class="brand-art"/><span>tiệm bánh tráng<small>G Ó C &nbsp; P H Ố &nbsp; N H Ỏ</small></span></a><div class="wallet"><span class="coin">₫</span><div><small>Trong két</small><strong>{{money(g.s.cash)}}</strong></div></div><div class="rank"><span>✦ Cấp {{g.shopLevel}}</span><small>{{names[g.shopLevel-1]}}</small><i><b :style="{width:progress+'%'}"></b></i></div><div class="top-actions"><button class="icon-btn" aria-label="Bật tắt âm thanh" @click="g.s.sound=!g.s.sound">{{g.s.sound?'♫':'♪'}}</button><button class="icon-btn" aria-label="Cài đặt" @click="g.dialog='settings'">⚙</button></div></header>
<main><div class="section-heading"><div><span class="eyebrow">MỘT CHÚT NGON · MỘT CHÚT THƯƠNG</span><h1>Hôm nay, mình bán gì?</h1></div><div class="day-badge"><span>{{g.s.day%3===0?'☂':'☀'}}</span><div><b>Ngày {{g.s.day}} · {{g.s.day%3===0?'Mưa đầu hẻm':'Nắng dịu'}}</b><small>{{g.s.relax?'Cứ thong thả nhé':`Còn ${Math.max(0,240-g.s.seconds)} giây`}}</small></div></div></div>
<div class="layout" :class="'tab-'+mobileTab"><div class="play-column"><section class="street" :class="g.s.day%3===0?'rain':'sun'" aria-label="Quầy bán hàng"><div class="scene-tint"></div><div class="shop-sign"><span>TIỆM BÁNH TRÁNG</span><small>Trộn chút vui • Cuốn chút thương</small></div><div class="scene-status"><span class="open-dot"></span>{{g.s.started?'Tiệm đang mở':'Chờ chủ tiệm mở cửa'}}<span class="spacer"></span>{{g.s.relax?'Chế độ thư giãn':'Giờ cao điểm'}}</div><div class="queue"><button v-for="q in g.r.queue" :key="q.id" class="customer" :class="{active:g.r.active===q.id}" @click="onSelectCustomer(q.id)"><span class="bubble"><b>{{recipe(q.recipe).name}}</b><small>{{g.r.active===q.id?'Đang làm cho mình ♡':'Chạm để nhận đơn'}}</small><div class="patience-wrap"><i class="patience"><b :style="{width:Math.max(0,q.left)/q.patience*100+'%'}"></b></i><span class="patience-time" :class="{urgent:q.left<=15}">⏱ {{q.left}}s</span></div></span><Sprite :index="customers[q.customer].sprite" class="person"/><span class="customer-name">{{customers[q.customer].name}}</span></button><div v-if="!g.s.started" class="start-card"><span class="eyebrow">NGÀY {{g.s.day}} · GÓC PHỐ NHỎ</span><h2>Chuẩn bị mở tiệm</h2><p>Ghé chợ nhập hàng, chăm chút tiệm nhỏ.<br>Bấm mở cửa để đón khách quen nhé!</p><button class="primary" @click="g.start">Mở cửa tiệm →</button><small>Chạm hoặc dùng chuột · Bật loa để nghe góc phố</small></div></div><button class="cat" aria-label="Vuốt ve mèo Cam" @click="g.play('cat');g.burst();g.notify('Mèo Cam: Meo~ Chúc tiệm đông khách!')"><Sprite :index="15"/><span>Mèo Cam</span></button></section><Station :g="g"/></div>
<aside><section class="chalkboard"><span class="board-flower">✳</span><p>Hôm nay ở tiệm</p><h2>Niềm vui nho nhỏ</h2><div class="chalk-line"></div><div class="stat"><span>Đã phục vụ</span><b>{{g.s.daily.served}} <small>khách</small></b></div><div class="stat"><span>Doanh thu</span><b>{{money(g.s.daily.revenue)}}</b></div><div class="stat"><span>Combo hiện tại</span><b>×{{g.s.combo}} ✦</b></div><div class="chalk-line"></div><div class="goal"><b>♡ Khách quen đầu hẻm</b><small>Phục vụ 3 khách trong ngày</small><progress :value="Math.min(g.s.daily.served,3)" max="3"></progress><button v-if="g.s.daily.served>=3&&!g.s.claimed.includes('day'+g.s.day)" class="reward" @click="g.quest">Nhận 15.000đ</button><span v-else>{{Math.min(g.s.daily.served,3)}}/3 · {{g.s.claimed.includes('day'+g.s.day)?'Đã nhận quà':'Quà: 15.000đ'}}</span></div><span class="chalk-doodle">— bán bằng cả trái tim —</span></section>
<section class="quick-card"><span class="eyebrow">CHĂM CHÚT TIỆM MÌNH</span><button v-for="[id,icon,title,sub] in [['stock','▦','Kho nguyên liệu','Nhập hàng, xem độ tươi'],['upgrades','✧','Nâng cấp tiệm','Mỗi ngày một xinh hơn'],['book','▤','Sổ công thức','7 món ngon góc phố'],['stories','✉','Thư khách quen','12 mẩu chuyện góc phố'],['fun','♧','Góc thư giãn','Bầu cua & quà mỗi ngày']]" :key="id" class="nav-btn" @click="g.dialog=id"><span class="nav-icon">{{icon}}</span><span>{{title}}<small>{{sub}}</small></span><b>›</b></button></section><section class="daily-note"><span>✉</span><p>“Một phần bánh tráng ngon<br>cũng đủ làm ngày vui hơn.”</p><small>— Lời nhắn từ góc phố</small></section><button class="end-day" :disabled="!g.s.started" @click="g.end">☾ Dọn tiệm, kết ngày</button><p class="save-note">✓ Tiến trình tự lưu trên thiết bị</p></aside></div></main>
<nav class="mobile-nav" aria-label="Điều hướng trên điện thoại"><button class="mobile-nav-item" :class="{active:mobileTab==='street'}" @click="mobileTab='street'"><span class="mobile-nav-icon">🏪<b v-if="g.r.queue.length" class="mobile-badge">{{g.r.queue.length}}</b></span><span>Quầy phố</span></button><button class="mobile-nav-item" :class="{active:mobileTab==='cook'}" @click="mobileTab='cook'"><span class="mobile-nav-icon">🥢<b v-if="g.dish" class="mobile-dot"></b></span><span>Chế biến</span></button><button class="mobile-nav-item" :class="{active:mobileTab==='board'}" @click="mobileTab='board'"><span class="mobile-nav-icon">📋</span><span>Bảng tiệm</span></button><button class="mobile-nav-item" :class="{active:mobileTab==='shop'}" @click="mobileTab='shop'"><span class="mobile-nav-icon">✧</span><span>Tiện ích</span></button></nav>
<footer><span>Góc phố nhỏ, niềm vui to.</span><span><button class="text-btn" @click="g.dialog='help'">Cách chơi</button> · <button class="text-btn" @click="g.dialog='cloud'">Liên kết tài khoản</button></span></footer>
<div id="toast" :class="{visible:g.toast && !g.dialog}" role="status" aria-live="polite">{{g.toast}}</div><div aria-hidden="true"><span v-for="p in g.particles" :key="p.id" class="particle" :style="{left:'50%',top:'50%','--dx':p.x+'px','--dy':p.y+'px','--rot':'30deg'}">✦</span></div>
<dialog ref="modal" @cancel="g.dialog=''" @close="g.dialog=''" @click="backgroundClose"><div class="toast-in-dialog" :class="{visible:g.toast && !!g.dialog}" role="status" aria-live="polite">{{g.toast}}</div><div class="modal-heading"><div><span class="eyebrow">TIỆM BÁNH TRÁNG</span><h2>{{titles[g.dialog]}}</h2></div><button class="icon-btn" aria-label="Đóng" @click="g.dialog=''">×</button></div><div class="modal-body">
<AccountPanel v-show="g.dialog==='cloud'" :state="g.s" @loaded="g.replaceState" @notice="g.notify"/>
<template v-if="g.dialog==='stock'"><p class="notice">Trong két <b>{{money(g.s.cash)}}</b> · Nhập mỗi lần 5 phần. Rau tươi có hạn sử dụng ngắn.</p><div class="stock-list"><div v-for="i in items" :key="i.id" class="stock-row"><Sprite :index="i.sprite"/><div><b>{{i.name}}</b><small>Còn {{count(g.s,i.id)}} · Giữ {{i.life+(i.type==='veg'?g.s.upgrades.fridge*2:0)}} ngày</small></div><button class="secondary" :disabled="g.s.cash<i.cost*5" @click="g.buy(i.id)">+5 · {{money(i.cost*5)}}</button></div></div><button v-if="g.s.cash<5000" class="primary wide" :disabled="g.s.rescueDay===g.s.day" @click="g.rescue">{{g.s.rescueDay===g.s.day?'Đã nhận hôm nay':'Nhận 50.000đ vốn khởi động lại'}}</button></template>
<template v-else-if="g.dialog==='upgrades'"><p class="notice">Cấp {{g.shopLevel}} · {{names[g.shopLevel-1]}}<br>Mở nướng ở 6 khách, cuốn ở 16 khách, tiệm nổi tiếng ở 35 khách.</p><div class="upgrade-list"><article v-for="u in upgrades" :key="u.id"><span class="upgrade-icon">{{u.icon}}</span><div><h3>{{u.name}}</h3><p>{{u.desc}}</p><small>Cấp {{g.s.upgrades[u.id]}}/{{u.max}}</small></div><button class="primary" :disabled="g.s.upgrades[u.id]>=u.max||g.s.cash<u.cost*(g.s.upgrades[u.id]+1)" @click="g.upgrade(u.id)">{{g.s.upgrades[u.id]>=u.max?'Đã tối đa':money(u.cost*(g.s.upgrades[u.id]+1))}}</button></article></div></template>
<template v-else-if="g.dialog==='book'"><div class="recipe-list"><article v-for="r in recipes" :key="r.id"><Sprite :index="r.sprite"/><div><span class="eyebrow">{{{mix:'TRỘN',grill:'NƯỚNG',roll:'CUỐN'}[r.method]}} · {{money(r.price)}}</span><h3>{{r.name}}</h3><p>{{r.ingredients.map(id=>items.find(i=>i.id===id).name).join(' + ')}}</p><small>{{g.shopLevel>=r.level?'✓ Đã mở công thức':`◇ Mở ở cấp ${r.level}`}}</small></div></article></div></template>
<template v-else-if="g.dialog==='stories'"><p class="notice">Phục vụ từng khách 3, 6 và 10 lần để mở thư. Mỗi phần quà chỉ nhận một lần.</p><div class="letters"><section v-for="(c,i) in customers" :key="c.name"><div class="letter-person"><Sprite :index="c.sprite"/><div><h3>{{c.name}}</h3><span>♡ {{g.s.friendships[i]}} lần ghé tiệm</span></div></div><article v-for="([title,body],j) in stories[i]" :key="j" :class="{locked:g.s.friendships[i]<storyMilestones[j]}"><h4>✉ {{title}}</h4><p>{{g.s.friendships[i]>=storyMilestones[j]?body:`Còn ${storyMilestones[j]-g.s.friendships[i]} lần phục vụ để mở thư.`}}</p><button v-if="g.s.friendships[i]>=storyMilestones[j]" class="secondary" :disabled="g.s.storyClaimed.includes(`${i}:${j}`)" @click="g.claimStory(i,j)">{{g.s.storyClaimed.includes(`${i}:${j}`)?'Đã nhận quà':`Nhận ${money([12000,20000,35000][j])}`}}</button></article></section></div></template>
<template v-else-if="g.dialog==='fun'"><div class="fun-card"><span class="big-symbol">✧</span><h3>Hộp quà đầu ngày</h3><p>Một chút may mắn cho tiệm nhỏ.</p><button class="primary" :disabled="g.s.lotteryDay===g.s.day" @click="g.lottery">{{g.s.lotteryDay===g.s.day?'Đã nhận hôm nay':'Mở quà miễn phí'}}</button></div><div class="fun-card"><h3>Bầu cua góc phố</h3><p>Chỉ dùng xu trong game, không quy đổi tiền thật.</p><div class="animal-options"><button v-for="(animal,i) in ['Bầu','Cua','Tôm','Cá','Gà','Nai']" :key="animal" class="secondary" @click="dice=g.gamble(i)">{{animal}}</button></div><p class="hint">5.000đ/lượt. Trùng mặt: hoàn cược và thưởng 5.000đ mỗi mặt. Không trùng: mất cược.</p><div v-if="dice" role="status"><div class="dice"><b v-for="(d,i) in dice.dice" :key="i">{{['Bầu','Cua','Tôm','Cá','Gà','Nai'][d]}}</b></div><p>{{dice.n?`Trùng ${dice.n} mặt!`:'Chưa gặp may lần này.'}}</p></div></div></template>
<template v-else-if="g.dialog==='settings'"><label class="setting-row"><span>Âm thanh thao tác & khách</span><input v-model="g.s.sound" type="checkbox"></label><label class="setting-row"><span>Nhạc nền góc phố</span><input v-model="g.s.music" type="checkbox"></label><label class="setting-row"><span>Âm lượng</span><input v-model.number="g.s.volume" type="range" min="0" max="1" step=".05"></label><label class="setting-row"><span>Chơi thư giãn<small>Khách không bỏ đi, tự chọn lúc kết ngày.</small></span><input v-model="g.s.relax" type="checkbox"></label><label class="setting-row"><span>Giảm chuyển động</span><input v-model="g.s.reduced" type="checkbox"></label><div class="notice">Phím 1–8 chọn nguyên liệu · Space chế biến · Enter phục vụ.</div><div class="button-row"><button class="secondary" @click="g.exportSave">Xuất bản lưu</button><label class="secondary file-label">Nhập bản lưu<input type="file" accept="application/json,.json" hidden @change="importFile"></label><button class="text-btn danger" @click="g.dialog='reset'">Chơi lại từ đầu</button></div></template>
<template v-else-if="g.dialog==='end'"><div class="summary"><span>☾</span><h3>Một ngày thật đáng yêu</h3><p>{{g.s.daily.served}} vị khách · Combo tốt nhất ×{{g.s.bestCombo}}</p><div class="stat"><span>Doanh thu</span><b>{{money(g.s.daily.revenue)}}</b></div><div class="stat"><span>Tiền nhập hàng</span><b>{{money(g.s.daily.expense)}}</b></div><div class="stat"><span>Chênh lệch thu / nhập</span><b>{{money(g.s.daily.revenue-g.s.daily.expense)}}</b></div><p class="notice">Hàng hết hạn được dọn; các đơn đang chờ sẽ kết thúc.</p><button class="primary wide" @click="g.next">Ngày mới, niềm vui mới →</button></div></template>
<template v-else-if="g.dialog==='help'"><div class="guide-box"><section class="guide-card"><div class="guide-title"><span class="guide-badge">1</span><h3>Nhận đơn & Chuẩn bị nguyên liệu</h3></div><p>Mỗi khách có thời gian chờ <b>50s – 80s</b> (đếm ngược ⏱ dưới đơn). Chạm vào khách để nhận đơn và xem công thức. Chọn đúng nguyên liệu trong khay rồi bấm <b>Bắt đầu chế biến</b>.</p></section><section class="guide-card"><div class="guide-title"><span class="guide-badge">2</span><h3>3 Phong cách chế biến</h3></div><ul class="guide-list"><li><b>✂ Bánh tráng trộn:</b> Cắt bánh đủ lần ➔ Canh kim rơi vào <b>vùng xanh</b> để đạt 3 sao ★★★.</li><li><b>♨ Bánh tráng nướng:</b> Chọn mức lửa ➔ Canh 2 mặt chín đều <b>62%–82%</b> ➔ Bấm <b>Lật bánh</b> ➔ Bấm <b>Nhấc bánh</b> khi chín đều (tránh 100% bị cháy).</li><li><b>↻ Bánh tráng cuốn:</b> Thêm sốt bơ, topping ➔ Canh nhịp cuốn bánh chặt tay.</li></ul></section><section class="guide-card"><div class="guide-title"><span class="guide-badge">3</span><h3>Phục vụ, Tiền boa & Combo</h3></div><p>• <b>Tiền boa tốc độ (+20%):</b> Phục vụ khi thanh chờ còn <b>trên 60%</b>.<br>• <b>Chuỗi Combo:</b> Phục vụ đúng liên tục giúp nhân thêm tiền thưởng.<br>• <b>Thân thiết:</b> Phục vụ đủ 3, 6, 10 lần để mở thư & nhận quà lớn.</p></section><section class="guide-card"><div class="guide-title"><span class="guide-badge">4</span><h3>Kho hàng & Chu kỳ ngày mới</h3></div><p>• Rau củ tươi có hạn sử dụng theo ngày. Mua <b>Tủ mát</b> để giữ thêm +2 ngày.<br>• Bấm <b>☾ Dọn tiệm, kết ngày</b> để dọn khách cũ. Sau đó thong thả <b>Ghé chợ nhập hàng</b> rồi bấm <b>Mở cửa tiệm</b> để đón khách mới!</p></section></div></template>
<template v-else-if="g.dialog==='level'"><div class="summary"><span>✦</span><h3>Cấp {{g.shopLevel}} · {{names[g.shopLevel-1]}}</h3><p>{{g.shopLevel===2?'Đã mở nướng Đà Lạt và trộn lá chanh!':g.shopLevel===3?'Đã mở cuốn bơ trứng và trộn hải vị!':'Cả góc phố đã biết tên tiệm mình rồi!'}}</p><button class="primary" @click="g.dialog=''">Bán tiếp nào!</button></div></template>
<template v-else-if="g.dialog==='discard'"><p>Nguyên liệu đã dùng sẽ không được hoàn lại.</p><div class="button-row"><button class="primary" @click="g.discard">Bỏ món, làm lại</button><button class="secondary" @click="g.dialog=''">Giữ món</button></div></template>
<template v-else-if="g.dialog==='reset'"><p>Tiến trình trên thiết bị sẽ được xóa. Có thể xuất bản lưu trước.</p><div class="button-row"><button class="secondary" @click="g.exportSave">Xuất bản lưu</button><button class="primary" @click="g.reset">Xóa và chơi lại</button></div></template>
<template v-else-if="g.dialog==='import'&&pending"><p>Bản lưu ngày {{pending.day}} · {{pending.served}} khách · {{money(pending.cash)}}. Thay thế tiến trình hiện tại?</p><div class="button-row"><button class="secondary" @click="g.exportSave">Xuất bản hiện tại</button><button class="primary" @click="imported">Nhập bản lưu</button></div></template>
</div></dialog></div>
</template>
