import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,level,count,purchase,consume,nextDay,award,validateSave,availableRecipes} from '../shared/engine.js';
test('fresh state valid, 19 stocked ingredients and 3 starter recipes',()=>{const s=fresh();assert.ok(validateSave(s));assert.equal(Object.keys(s.inventory).length,19);assert.equal(availableRecipes(s).length,3);});
test('purchase charges exactly, rejects overspend and consumes FIFO',()=>{let s=fresh(),before=s.cash;assert.ok(purchase(s,'mango',5));assert.equal(s.cash,before-7500);assert.equal(count(s,'mango'),13);assert.ok(consume(s,'mango'));assert.equal(count(s,'mango'),12);s.cash=0;assert.equal(purchase(s,'beef'),false);assert.equal(purchase(s,'beef',-5),false);});
test('new day expires fresh vegetables, refrigerator extends new batches',()=>{let s=fresh();nextDay(s);assert.equal(count(s,'mango'),0);assert.equal(count(s,'paper'),8);s.upgrades.fridge=1;purchase(s,'mango');nextDay(s);assert.equal(count(s,'mango'),5);});
test('correct recipe pays plus tip, wrong recipe resets combo and pays nothing',()=>{let s=fresh(),o={recipe:'classic'},b=s.cash;let r=award(s,o,['paper','mango','shrimp','salt'],3,1);assert.ok(r.tip>0);assert.equal(s.cash,b+r.total);assert.equal(s.served,1);assert.equal(s.combo,1);let bad=award(s,o,['paper','mango','beef','salt'],3,1);assert.equal(bad.total,0);assert.equal(s.combo,0);assert.equal(s.served,1);});
test('progression opens grill at 6, roll at 16, max at 35 customers',()=>{let s=fresh();s.served=6;assert.equal(level(s),2);assert.equal(availableRecipes(s).length,5);s.served=16;assert.equal(level(s),3);assert.equal(availableRecipes(s).length,7);s.served=35;assert.equal(level(s),4);});
test('save validation rejects bad economy, inventory and schema',()=>{assert.equal(validateSave({}),false);let s=fresh();s.cash=-1;assert.equal(validateSave(s),false);s=fresh();s.inventory.paper[0].qty=-9;assert.equal(validateSave(s),false);s=fresh();s.daily=null;assert.equal(validateSave(s),false);});

// v2.1: thermal simulation, resumable service and friendship rewards.
const {emptyGrill,advanceGrill,grillQuality,validRuntime,migrate,storyReward}=await import('../shared/mechanics.js');
test('grill heats the active side only; perfect, raw and burnt outcomes',()=>{const g=emptyGrill();for(let i=0;i<100;i++)advanceGrill(g,.1);assert.ok(g.temperature>170);assert.ok(g.sides[0]>.5);assert.equal(g.sides[1],0);assert.equal(grillQuality(g),0);g.side=1;for(let i=0;i<95;i++)advanceGrill(g,.1);assert.equal(grillQuality(g),3);for(let i=0;i<70;i++)advanceGrill(g,.1);assert.equal(grillQuality(g),0);assert.ok(g.sides[1]>=1);});
test('burnt or raw food receives zero revenue even with correct ingredients',()=>{let s=fresh(),before=s.cash;assert.equal(award(s,{recipe:'grill'},['sesame','egg','shrimp','butter'],0,1).total,0);assert.equal(s.cash,before);assert.equal(s.served,0);});
test('runtime roundtrip preserves consumed stock, active customer and grill sides',()=>{let s=fresh();s.started=true;consume(s,'sesame');s.runtime={queue:[{id:1,recipe:'grill',customer:0,left:80,patience:105}],active:1,selected:['sesame','egg','shrimp','butter'],phase:'cook',hits:[],cut:0,seq:1,grill:{temperature:180,power:2,side:1,sides:[.7,.3]}};let loaded=JSON.parse(JSON.stringify(s));assert.ok(validateSave(loaded));assert.equal(count(loaded,'sesame'),7);assert.equal(loaded.runtime.grill.sides[0],.7);loaded.runtime.active=99;assert.equal(validateSave(loaded),false);});
test('corrupt saved phases and invalid thermal values are rejected',()=>{let r={queue:[],active:null,selected:[],phase:'ready',hits:[3],cut:0,seq:0,grill:emptyGrill()};assert.equal(validRuntime(r),false);r.phase='select';r.grill.temperature=NaN;assert.equal(validRuntime(r),false);});
test('old saves migrate without resetting money or progress',()=>{let s=fresh();delete s.friendships;delete s.storyClaimed;delete s.runtime;s.cash=333000;s.served=16;assert.ok(validateSave(s));migrate(s);assert.equal(s.cash,333000);assert.equal(s.served,16);assert.deepEqual(s.friendships,[0,0,0,0]);});
test('letters unlock per customer and rewards can only be claimed once',()=>{let s=fresh();assert.equal(storyReward(s,0,0),0);s.friendships[0]=3;assert.equal(storyReward(s,0,0),12000);assert.equal(storyReward(s,0,0),0);assert.equal(storyReward(s,1,0),0);s.friendships[0]=10;assert.equal(storyReward(s,0,2),35000);assert.ok(validateSave(s));});
