import express from 'express';import cors from 'cors';import helmet from 'helmet';import {rateLimit} from 'express-rate-limit';import mongoose from 'mongoose';import crypto from 'node:crypto';
import {User,Session,MediaAsset} from './models.js';import {authenticate,credentials,hashPassword,checkPassword,sessionFor} from './auth.js';import {validateSave} from '../../shared/engine.js';
const error=(status,message)=>Object.assign(Error(message),{status});
export function createApp(config){const app=express();app.disable('x-powered-by');app.set('trust proxy',config.trustProxy);app.use(helmet());app.use(cors({origin(origin,cb){if(!origin||config.origins.includes(origin))return cb(null,true);cb(error(403,'Origin chưa được cho phép. Cấu hình CLIENT_ORIGINS.'));},methods:['GET','POST','PUT','OPTIONS'],allowedHeaders:['Content-Type','Authorization']}));app.use(express.json({limit:'512kb'}));app.use('/api',(_req,res,next)=>{res.set('Cache-Control','no-store');next()});
 app.get('/api/health',(_req,res)=>res.status(mongoose.connection.readyState===1?200:503).json({ok:mongoose.connection.readyState===1,version:'3.0.0',database:mongoose.connection.readyState===1?'connected':'unavailable'}));
 app.get('/api/media/manifest',async(_req,res)=>{const rows=await MediaAsset.find().lean();res.json({assets:Object.fromEntries(rows.map(x=>[x.key,x.secureUrl]))});});
 const authLimiter=rateLimit({windowMs:60000,limit:20,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Thử lại sau một phút.'}});
 app.post('/api/auth/register',authLimiter,async(req,res)=>{const {username,password}=credentials(req.body);if(await User.exists({username}))throw error(409,'Tên tài khoản đã tồn tại.');const hashed=await hashPassword(password);const user=await User.create({username,...hashed,code:crypto.randomBytes(6).toString('hex').toUpperCase()});res.status(201).json(await sessionFor(user));});
 app.post('/api/auth/login',authLimiter,async(req,res)=>{const {username,password}=credentials(req.body),user=await User.findOne({username}).select('+salt +passwordHash');if(!await checkPassword(password,user))throw error(401,'Sai tài khoản hoặc mật khẩu.');res.json(await sessionFor(user));});
 app.use('/api',authenticate);
 app.get('/api/auth/me',(req,res)=>res.json({username:req.user.username,code:req.user.code}));
 app.post('/api/auth/logout',async(req,res)=>{await Session.deleteOne({hash:req.sessionHash});res.json({ok:true})});
 app.get('/api/account/save',(req,res)=>res.json({saveData:req.user.saveData,revision:req.user.revision}));
 app.put('/api/account/save',async(req,res)=>{const {saveData,revision}=req.body||{};if(!Number.isInteger(revision)||revision<0||!validateSave(saveData))throw error(400,'Bản lưu hoặc phiên bản không hợp lệ.');const updated=await User.findOneAndUpdate({_id:req.user._id,revision},{$set:{saveData},$inc:{revision:1}},{new:true,runValidators:true}).select('revision');if(!updated)throw error(409,'Bản máy chủ mới hơn. Xuất bản hiện tại, tải bản mới rồi thử lại.');res.json({revision:updated.revision});});
 app.get('/api/referral/me',(req,res)=>res.json({code:req.user.code,pendingAmount:req.user.pendingAmount}));
 app.post('/api/referral/claim',async(req,res)=>{const code=typeof req.body?.code==='string'?req.body.code.trim().toUpperCase():'';if(!/^[A-F0-9]{10,12}$/.test(code))throw error(400,'Mã giới thiệu không hợp lệ.');await mongoose.connection.transaction(async session=>{const friend=await User.findOne({code}).session(session);if(!friend||friend._id.equals(req.user._id))throw error(400,'Mã không tồn tại hoặc là mã của bạn.');const me=await User.findOneAndUpdate({_id:req.user._id,referredBy:null},{$set:{referredBy:friend._id},$inc:{pendingAmount:300000}},{new:true,session});if(!me)throw error(409,'Bạn đã nhận mã giới thiệu trước đó.');await User.updateOne({_id:friend._id},{$inc:{pendingAmount:300000}},{session});});res.json({ok:true,amount:300000});});
 // Transfer the reward into the authoritative saved snapshot in one transaction.
 // A retry returns the existing updated save, never a duplicate client-side credit.
 app.post('/api/referral/rewards/take',async(req,res)=>{if(!Number.isInteger(req.body?.revision))throw error(400,'Thiếu phiên bản bản lưu.');let output;await mongoose.connection.transaction(async session=>{const me=await User.findById(req.user._id).session(session);if(!me.saveData)throw error(400,'Lưu tiến trình lên máy chủ trước khi nhận quà.');if(!me.pendingAmount){output={amount:0,saveData:me.saveData,revision:me.revision};return;}if(me.revision!==req.body.revision)throw error(409,'Bản lưu đã thay đổi. Tải bản mới trước khi nhận quà.');const amount=me.pendingAmount;me.saveData={...me.saveData,cash:me.saveData.cash+amount};if(!validateSave(me.saveData))throw error(400,'Bản lưu vượt giới hạn.');me.markModified('saveData');me.pendingAmount=0;me.revision++;await me.save({session});output={amount,saveData:me.saveData,revision:me.revision};});res.json(output);});
 app.use((_req,res)=>res.status(404).json({error:'Không tìm thấy API. Frontend chạy riêng ở cổng 5173.'}));
 app.use((err,_req,res,_next)=>{if(err.code===11000)return res.status(409).json({error:'Tên tài khoản hoặc dữ liệu đã tồn tại.'});const status=err.status||500;if(status>=500)console.error('API error:',err.name);res.status(status).json({error:status<500?err.message:'Máy chủ gặp lỗi. Kiểm tra kết nối MongoDB; tính năng bạn bè cần replica set hoặc Atlas.'});});return app;
}
