import {migrate,validRuntime} from './mechanics.js';
import {items,recipes,recipe} from './data.js';
export const SAVE_KEY='gocpho-save-v2';
export function fresh(){return {version:2,day:1,cash:150000,xp:0,served:0,stars:0,combo:0,bestCombo:0,inventory:Object.fromEntries(items.map(i=>[i.id,[{qty:8,expires:1+i.life}]])),upgrades:{tools:0,fridge:0,decor:0,assistant:0},daily:{served:0,revenue:0,expense:0,waste:0},claimed:[],lotteryDay:0,rescueDay:0,relax:true,sound:true,music:true,volume:.55,reduced:false,started:false,seconds:0,dayLength:240,friendships:[0,0,0,0],storyClaimed:[],runtime:null};}
export function level(s){return s.served>=35?4:s.served>=16?3:s.served>=6?2:1;}
export function count(s,id){return (s.inventory[id]||[]).reduce((a,b)=>a+b.qty,0);}
export function consume(s,id){let batches=s.inventory[id];if(!batches)return false;let b=batches.find(b=>b.qty>0);if(!b)return false;b.qty--;s.inventory[id]=batches.filter(x=>x.qty>0);return true;}
export function purchase(s,id,qty=5){const i=items.find(x=>x.id===id);if(!i||!Number.isInteger(qty)||qty<1||qty>100)return false;const cost=i.cost*qty;if(s.cash<cost)return false;s.cash-=cost;s.daily.expense+=cost;s.inventory[id].push({qty,expires:s.day+i.life+(i.type==='veg'?s.upgrades.fridge*2:0)});return true;}
export function nextDay(s){s.day++;let waste=0;for(const i of items){let expired=s.inventory[i.id].filter(b=>b.expires<=s.day);waste+=expired.reduce((n,b)=>n+b.qty,0);s.inventory[i.id]=s.inventory[i.id].filter(b=>b.expires>s.day);}s.seconds=0;s.daily={served:0,revenue:0,expense:0,waste};s.combo=0;return waste;}
export function scoreDish(order,selected,quality){const r=recipe(order.recipe);if(!r||!Number.isFinite(quality)||quality<=0)return 0;const exact=r.ingredients.length===selected.length&&r.ingredients.every(x=>selected.includes(x));return exact?Math.max(1,Math.min(3,Math.round(quality))):0;}
export function award(s,order,selected,quality,remaining){const stars=scoreDish(order,selected,quality);if(!stars){s.combo=0;return {stars:0,total:0,tip:0};}const r=recipe(order.recipe);s.combo++;s.bestCombo=Math.max(s.bestCombo,s.combo);let tip=Math.round(r.price*(stars/3*.15+Math.min(s.combo,8)*.025)*(1+s.upgrades.decor*.1)*(remaining>0.6?1.2:1));const total=r.price+tip;s.cash+=total;s.xp+=stars*10;s.served++;s.stars+=stars;s.daily.served++;s.daily.revenue+=total;return {stars,total,tip};}
export function validateSave(s){if(!s||s.version!==2)return false;if(!validRuntime(s.runtime))return false;if(s.friendships!==undefined&&(!Array.isArray(s.friendships)||s.friendships.length!==4||!s.friendships.every(n=>Number.isInteger(n)&&n>=0&&n<=1e8)))return false;if(s.storyClaimed!==undefined&&(!Array.isArray(s.storyClaimed)||s.storyClaimed.length>12||!s.storyClaimed.every(k=>/^[0-3]:[0-2]$/.test(k))))return false;if(!['relax','sound','music','reduced','started'].every(k=>typeof s[k]==='boolean')||!Number.isFinite(s.volume)||s.volume<0||s.volume>1)return false;for(const k of ['day','cash','xp','served','stars','seconds','bestCombo','lotteryDay','rescueDay','combo','dayLength'])if(!Number.isFinite(s[k])||s[k]<0||s[k]>1e10)return false;if(!Array.isArray(s.claimed)||s.claimed.some(x=>typeof x!=='string'))return false;if(!s.daily||!['served','revenue','expense','waste'].every(k=>Number.isFinite(s.daily[k])&&s.daily[k]>=0))return false;if(!s.upgrades||!['tools','fridge','decor','assistant'].every(k=>Number.isInteger(s.upgrades[k])&&s.upgrades[k]>=0&&s.upgrades[k]<=3))return false;return items.every(i=>Array.isArray(s.inventory?.[i.id])&&s.inventory[i.id].length<500&&s.inventory[i.id].every(b=>Number.isInteger(b.qty)&&b.qty>=0&&b.qty<=10000&&Number.isInteger(b.expires)&&b.expires>=0));}
export function load(){try{let s=JSON.parse(localStorage.getItem(SAVE_KEY));if(validateSave(s))return migrate(s);}catch{}return fresh();}
export function save(s){try{localStorage.setItem(SAVE_KEY,JSON.stringify(s));return true;}catch{return false;}}
export function availableRecipes(s){return recipes.filter(r=>r.level<=level(s));}
